/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author austere
 */
public class FeedRateConfigurationVfdPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedRateVfd
     */
    public FeedRateConfigurationVfdPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FeedrateVdfPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FeedRateVfd = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        VfdFrequency = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        FeedRateVdfDelay = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        VdfMachineNAme = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        vdfDrivetype = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vdfDriveAxis = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1680, 1080));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setPreferredSize(new java.awt.Dimension(1650, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        FeedrateVdfPanel.setBackground(new java.awt.Color(255, 155, 53));
        FeedrateVdfPanel.setPreferredSize(new java.awt.Dimension(1650, 990));

        jPanel3.setBackground(new java.awt.Color(238, 218, 96));

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        jLabel6.setText("Feed Rates Configuration VFD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(254, 207, 160));

        jLabel5.setText("Feed Rate");

        FeedRateVfd.setText("0");
        FeedRateVfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedRateVfdActionPerformed(evt);
            }
        });
        FeedRateVfd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FeedRateVfdKeyReleased(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(254, 207, 160));

        VfdFrequency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3" }));
        VfdFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VfdFrequencyActionPerformed(evt);
            }
        });

        jLabel8.setText("Frequency (Hz)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(VfdFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VfdFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 203, 151));

        jLabel7.setText("Delay (ms)");

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/icons-minus-20.png"))); // NOI18N
        jButton14.setMaximumSize(new java.awt.Dimension(25, 29));
        jButton14.setMinimumSize(new java.awt.Dimension(25, 29));
        jButton14.setPreferredSize(new java.awt.Dimension(20, 29));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        FeedRateVdfDelay.setText("0");
        FeedRateVdfDelay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedRateVdfDelayActionPerformed(evt);
            }
        });
        FeedRateVdfDelay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FeedRateVdfDelayKeyReleased(evt);
            }
        });

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/icons-plus-20.png"))); // NOI18N
        jButton16.setMaximumSize(new java.awt.Dimension(18, 29));
        jButton16.setMinimumSize(new java.awt.Dimension(18, 29));
        jButton16.setPreferredSize(new java.awt.Dimension(18, 29));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FeedRateVdfDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedRateVdfDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/icons-save--20.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/icons-clear-20.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/icons8-delete-bin-20.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedRateVfd, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton23)
                .addGap(39, 39, 39)
                .addComponent(jButton24)
                .addGap(32, 32, 32)
                .addComponent(jButton20)
                .addGap(43, 43, 43))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton24)
                                    .addComponent(jButton23)
                                    .addComponent(jButton20)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FeedRateVfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTable1.setBackground(new java.awt.Color(254, 187, 99));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine Name", "Drive Type", "Axis", "Feed Rate", "Frequency(Hz)", "Delay(ms)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel12.setBackground(new java.awt.Color(238, 218, 96));

        jButton4.setBackground(new java.awt.Color(69, 157, 216));
        jButton4.setText("SAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 187, 0));
        jButton5.setText("DISCARD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(220, 82, 238));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel6.setBackground(new java.awt.Color(235, 166, 97));

        jLabel12.setText("Machine Name");

        VdfMachineNAme.setText("My Machine");
        VdfMachineNAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VdfMachineNAmeActionPerformed(evt);
            }
        });

        jLabel13.setText("Drive Type");

        vdfDrivetype.setText(" VFD");
        vdfDrivetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdfDrivetypeActionPerformed(evt);
            }
        });

        jLabel14.setText("Axis");

        vdfDriveAxis.setText(" X");
        vdfDriveAxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdfDriveAxisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel12)
                .addGap(57, 57, 57)
                .addComponent(VdfMachineNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vdfDrivetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(vdfDriveAxis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VdfMachineNAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(vdfDrivetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(vdfDriveAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FeedrateVdfPanelLayout = new javax.swing.GroupLayout(FeedrateVdfPanel);
        FeedrateVdfPanel.setLayout(FeedrateVdfPanelLayout);
        FeedrateVdfPanelLayout.setHorizontalGroup(
            FeedrateVdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FeedrateVdfPanelLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(FeedrateVdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        FeedrateVdfPanelLayout.setVerticalGroup(
            FeedrateVdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedrateVdfPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(FeedrateVdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FeedrateVdfPanelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedrateVdfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FeedrateVdfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FeedRateVfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedRateVfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeedRateVfdActionPerformed

    private void FeedRateVfdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FeedRateVfdKeyReleased
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        System.err.println(key);
        if ((key >= 48 && key <= 57) || (key >= 96 && key <= 105) || (key == 46) || (key == 8)) {
            FeedRateVfd.setText(FeedRateVfd.getText());
        } else {
            FeedRateVfd.setText("0");

        }
    }//GEN-LAST:event_FeedRateVfdKeyReleased

    private void VfdFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VfdFrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VfdFrequencyActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (!FeedRateVdfDelay.getText().isEmpty()) {
            int StopDelay = Integer.parseInt(FeedRateVdfDelay.getText());
            if (StopDelay > 0) {
                StopDelay = StopDelay - 1;
                FeedRateVdfDelay.setText(Integer.toString(StopDelay));
            }
        } else {
            FeedRateVdfDelay.setText(Integer.toString(0));
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void FeedRateVdfDelayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedRateVdfDelayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeedRateVdfDelayActionPerformed

    private void FeedRateVdfDelayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FeedRateVdfDelayKeyReleased
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        System.err.println(key);
        if ((key >= 48 && key <= 57) || (key >= 96 && key <= 105) || (key == 46) || (key == 8) || (key == 190)) {
            FeedRateVdfDelay.setText(FeedRateVdfDelay.getText());
        } else {
            FeedRateVdfDelay.setText("0");

        }
    }//GEN-LAST:event_FeedRateVdfDelayKeyReleased

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!FeedRateVdfDelay.getText().isEmpty()) {
            int StopDelay = Integer.parseInt(FeedRateVdfDelay.getText());
            if (StopDelay <= 9998) {
                StopDelay = StopDelay + 1;
                FeedRateVdfDelay.setText(Integer.toString(StopDelay));
            } else {
                JFrame f = new JFrame("Error");
                JPanel p = new JPanel();
                JLabel l = null;
                l = new JLabel("Delay should be less than 9999 ");
                p.add(l);
                f.add(p);
                l.setHorizontalAlignment(JLabel.CENTER);
                l.setVerticalAlignment(JLabel.CENTER);
                l.setPreferredSize(new Dimension(250, 50));
                l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
                f.setBounds(350, 350, 600, 100);
                l.setForeground(Color.red);
                f.show();

            }
        } else {
            FeedRateVdfDelay.setText(Integer.toString(0));
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:newTask();

        newTask();
    }//GEN-LAST:event_jButton23ActionPerformed
  private boolean newTask() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        JFrame f = new JFrame("Error");
        JPanel p = new JPanel();
        JLabel l = null;
        String FeedRate = FeedRateVfd.getText();
        String Frequency1 = VfdFrequency.getSelectedItem().toString();
        String Delay1 = FeedRateVdfDelay.getText();
        String MachineName = VdfMachineNAme.getText();
        String DriveType = vdfDrivetype.getText();
        String Axis = vdfDriveAxis.getText();

        if (MachineName.isEmpty() || DriveType.isEmpty() || Axis.isEmpty() || FeedRate.isEmpty() || Frequency1.equals("Select") || Delay1.isEmpty()) {

            if (MachineName.isEmpty()) {
                l = new JLabel("MachineName Empty");
                p.add(l);
                f.add(p);
                f.setLocation(400, 350);
                f.setSize(800, 100);
                f.show();
                return false;
            }
            if (DriveType.isEmpty()) {
                l = new JLabel("DriveType Empty");
                  l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            l.setForeground(Color.red);
            f.setBounds(350, 350, 600, 100);
            p.add(l);
            f.add(p);
                f.show();
                return false;
            }
            if (Axis.isEmpty()) {
                l = new JLabel("Axis Empty");
                 l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            l.setForeground(Color.red);
            f.setBounds(350, 350, 600, 100);
            p.add(l);
            f.add(p);
                f.show();
                return false;
            }
            if (FeedRate.isEmpty()) {
                l = new JLabel("FeedRate Empty");
                l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            l.setForeground(Color.red);
            f.setBounds(350, 350, 600, 100);
            p.add(l);
            f.add(p);
                f.show();
                return false;
            }
            if (Frequency1.equals("Select")) {
                l = new JLabel("Frequency Empty");
               l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            l.setForeground(Color.red);
            f.setBounds(350, 350, 600, 100);
            p.add(l);
            f.add(p);
                f.show();
                return false;
            }
            if (Delay1.isEmpty()) {
                l = new JLabel("Delay Empty");
               l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            l.setForeground(Color.red);
            f.setBounds(350, 350, 600, 100);
            p.add(l);
            f.add(p);
                f.show();
                return false;
            }

        } else {

            model.addRow(new Object[]{MachineName, DriveType, Axis, FeedRate, Frequency1, Delay1});
            System.err.println("new Task");
            FeedRateVfd.setText("0");
            FeedRateVdfDelay.setText("0");
//            jTextField1.setText("");
//            jTextField2.setText("");
//            jTextField3.setText("");

        }
        return true;
    }
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:

        FeedRateVfd.setText("");
        FeedRateVdfDelay.setText("");
        //        jTextField1.setText("");
        //        jTextField2.setText("");
        //        jTextField3.setText("");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        //        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //        model.removeRow(TableIndex);
        //        System.err.println("Removed Row " + TableIndex);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        //        System.err.println(index);
        //        System.err.println(TableIndex);

        if (index != -1) {
            if (index >= 0) {
                JFrame f = new JFrame("Error");
                JPanel p = new JPanel();
                JLabel l = null;

                String machinename = VdfMachineNAme.getText();
                if (machinename.isEmpty()) {
                    l = new JLabel("Please select record ");
                    p.add(l);
                    f.add(p);
                    l.setHorizontalAlignment(JLabel.CENTER);
                    l.setVerticalAlignment(JLabel.CENTER);
                    l.setPreferredSize(new Dimension(250, 50));
                    l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
                    f.setBounds(350, 350, 600, 100);
                    l.setForeground(Color.red);
                    f.show();

                } else {
                    model.removeRow(TableIndex);
                    System.err.println("Removed Row " + TableIndex);
                }

                FeedRateVfd.setText("0");
                VfdFrequency.setSelectedIndex(0);

            }
        } else {

            JFrame f = new JFrame("Error");
            JPanel p = new JPanel();
            JLabel l = null;
            l = new JLabel("Please select or insert record ");
            p.add(l);
            f.add(p);
            l.setHorizontalAlignment(JLabel.CENTER);
            l.setVerticalAlignment(JLabel.CENTER);
            l.setPreferredSize(new Dimension(250, 50));
            l.setFont(new Font("DIALOG_INPUT", Font.PLAIN, 14));
            f.setBounds(350, 350, 600, 100);
            l.setForeground(Color.red);
            f.show();

        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        String MachineName = model.getValueAt(index, 0).toString();
        String Drivetype = model.getValueAt(index, 1).toString();
        String Axis = model.getValueAt(index, 2).toString();
        String FeedRate = model.getValueAt(index, 3).toString();
        String Delay = model.getValueAt(index, 5).toString();
        FeedRateVfd.setText(FeedRate);

        VfdFrequency.getSelectedItem().toString();
        FeedRateVdfDelay.setText(Delay);
        VdfMachineNAme.setText(MachineName);
        vdfDrivetype.setText(Drivetype);
        vdfDriveAxis.setText(Axis);
        TableIndex = index;
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

      Createmachinepanel Createmachinepanel =new Createmachinepanel();
          FeedrateVdfPanel.setVisible(false);
        setLayout(new BorderLayout());
        add(Createmachinepanel);
        revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void VdfMachineNAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VdfMachineNAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VdfMachineNAmeActionPerformed

    private void vdfDrivetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdfDrivetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdfDrivetypeActionPerformed

    private void vdfDriveAxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdfDriveAxisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdfDriveAxisActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Createmachinepanel Createmachinepanel =new Createmachinepanel();
          FeedrateVdfPanel.setVisible(false);
        setLayout(new BorderLayout());
        add(Createmachinepanel);
        revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private int TableIndex;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FeedRateVdfDelay;
    private javax.swing.JTextField FeedRateVfd;
    private javax.swing.JPanel FeedrateVdfPanel;
    private javax.swing.JTextField VdfMachineNAme;
    private javax.swing.JComboBox<String> VfdFrequency;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField vdfDriveAxis;
    private javax.swing.JTextField vdfDrivetype;
    // End of variables declaration//GEN-END:variables
}
